version: "3.7"

volumes:
  db:
  nats_storage:

services:
  app:
    build:
      context: .
      dockerfile: ./build/dev.Dockerfile
    ports:
      - "7777:8080"
    environment:
      GIN_MODE: 'release'
      CONFIG_FILE: './configs/config.yml'
    volumes:
      - .:/app
    depends_on:
      nats:
        condition: service_healthy

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
  nats:
    image: nats:2.10.9-alpine3.19
    command: nats-server -js --config /etc/nats/nats-server.conf
    healthcheck:
      test: echo $$(wget --server-response http://localhost:8222/varz 2>&1 | grep  '200 OK') | grep '200'  || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "8222:8222"
      - "4222:4222"
    volumes:
      - ./configs/nats-server.conf:/etc/nats/nats-server.conf
      - nats_storage:/nats/storage