// Code generated by go-swagger; DO NOT EDIT.

// Package restapi TrackChecker App
//
//	This is a server for tracking parcels
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//	Contact: Aleksei Poliakov<sozdaibk@gmail.com> https://apoldev.t.me/
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
