// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a server for tracking parcels",
    "title": "TrackChecker App",
    "contact": {
      "name": "Aleksei Poliakov",
      "url": "https://apoldev.t.me/",
      "email": "sozdaibk@gmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost:7777",
  "basePath": "/",
  "paths": {
    "/track": {
      "get": {
        "description": "get tracking numbers results",
        "summary": "Tracking",
        "operationId": "getResults",
        "parameters": [
          {
            "type": "string",
            "description": "Tracking ID",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "tracking result is found",
            "schema": {
              "$ref": "#/definitions/trackingResult"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "description": "Create tracking request with some tracking numbers",
        "consumes": [
          "application/json"
        ],
        "summary": "Tracking",
        "parameters": [
          {
            "description": "Request body",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/trackRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/requestResult"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "requestResult": {
      "type": "object",
      "properties": {
        "tracking_id": {
          "type": "string"
        },
        "tracking_numbers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/trackingNumber"
          }
        }
      }
    },
    "result": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/spiderResults"
          }
        },
        "status": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "spiderResults": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string",
          "example": "error message"
        },
        "execute_time": {
          "type": "number",
          "example": "1.234"
        },
        "result": {
          "type": "object",
          "example": {
            "CountryFrom": "RU",
            "CountryTo": "US",
            "events": [
              {
                "date": "2021-01-01T00:00:00Z",
                "place": "New York",
                "status": "In Transit"
              }
            ]
          }
        },
        "spider": {
          "type": "string",
          "example": "usps"
        },
        "tracking_number": {
          "type": "string",
          "example": "1234567890"
        }
      }
    },
    "trackRequest": {
      "type": "object",
      "required": [
        "tracking_numbers"
      ],
      "properties": {
        "tracking_numbers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "trackingNumber": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "trackingResult": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/result"
          }
        },
        "error": {
          "type": "string"
        },
        "status": {
          "type": "boolean"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a server for tracking parcels",
    "title": "TrackChecker App",
    "contact": {
      "name": "Aleksei Poliakov",
      "url": "https://apoldev.t.me/",
      "email": "sozdaibk@gmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost:7777",
  "basePath": "/",
  "paths": {
    "/track": {
      "get": {
        "description": "get tracking numbers results",
        "summary": "Tracking",
        "operationId": "getResults",
        "parameters": [
          {
            "type": "string",
            "description": "Tracking ID",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "tracking result is found",
            "schema": {
              "$ref": "#/definitions/trackingResult"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "description": "Create tracking request with some tracking numbers",
        "consumes": [
          "application/json"
        ],
        "summary": "Tracking",
        "parameters": [
          {
            "description": "Request body",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/trackRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/requestResult"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "requestResult": {
      "type": "object",
      "properties": {
        "tracking_id": {
          "type": "string"
        },
        "tracking_numbers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/trackingNumber"
          }
        }
      }
    },
    "result": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/spiderResults"
          }
        },
        "status": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "spiderResults": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string",
          "example": "error message"
        },
        "execute_time": {
          "type": "number",
          "example": "1.234"
        },
        "result": {
          "type": "object",
          "example": {
            "CountryFrom": "RU",
            "CountryTo": "US",
            "events": [
              {
                "date": "2021-01-01T00:00:00Z",
                "place": "New York",
                "status": "In Transit"
              }
            ]
          }
        },
        "spider": {
          "type": "string",
          "example": "usps"
        },
        "tracking_number": {
          "type": "string",
          "example": "1234567890"
        }
      }
    },
    "trackRequest": {
      "type": "object",
      "required": [
        "tracking_numbers"
      ],
      "properties": {
        "tracking_numbers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "trackingNumber": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "trackingResult": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/result"
          }
        },
        "error": {
          "type": "string"
        },
        "status": {
          "type": "boolean"
        }
      }
    }
  }
}`))
}
