// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TrackResultRepo is an autogenerated mock type for the TrackResultRepo type
type TrackResultRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *TrackResultRepo) Get(id string) ([]byte, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: id, b
func (_m *TrackResultRepo) Set(id string, b []byte) error {
	ret := _m.Called(id, b)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(id, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrackResultRepo creates a new instance of TrackResultRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackResultRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackResultRepo {
	mock := &TrackResultRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
