name: Deploy to server

on:
  push:
    branches:
      - develop_apoldev
      - feature/actions
  merge_group:
    branches:
      - develop_apoldev

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
  tests:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: docker://golang:1.21
        with:
          args: go test ./...
  docker:
    needs: [lint, tests]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tags: "ghcr.io/apoldev/trackchecker:latest"
          file: "build/prod.Dockerfile"
  deploy:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Copy to host
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DOCKER_SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.HOST }} "mkdir -p /root/trackchecker"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ secrets.HOST }}:/root/trackchecker
        env:
          DOCKER_SSH_PRIVATE_KEY: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      - name: Deploy stack on remote server
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.HOST }} "\
          docker stack deploy -c /root/trackchecker/stack.yml trackcheckerci"