name: Deploy to server

on:
  push:
    branches:
      - feature/actions

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: docker://golangci/golangci-lint:latest
        with:
          args: golangci-lint run --timeout 5m0s --skip-dirs vendor --skip-files *_test.go